### ISSUE TITLE
Please make one for firefox

### ISSUE THREAD

**Issue by OmkarK45** [Skilled-Coder/New-jiosaavn-downloader-chrome-extension#1]
Hey buddy, thanks for this extension can you make one for Firefox as well ?

**Comment by Skilled-Coder** [comment]
Extension for firefox coming soon!
If you like my work, please star the repository

**Comment by OmkarK45** [comment]
Hey buddy, any update on the Firefox extension ? Thanks a ton by the way.

**Comment by Skilled-Coder** [comment]
Having some issues with firefox and opera addon...but i will solve them soon! Stay tuned..

**Comment by OmkarK45** [comment]
Thank you so much <3 ... Waiting !

**Comment by Skilled-Coder** [comment]
Thanks for waiting!
Jiosaavn downloader for firefox is coming soon!

**Comment by OmkarK45** [comment]
Appreciate your hardwork sir :)

**Comment by Skilled-Coder** [comment]
https://github.com/Skilled-Coder/New-Jiosaavn-downloader-mozilla-addon
:)
