### ISSUE TITLE
Please Make One For Gaana.com

### ISSUE THREAD

**Issue by shivamrewa9981** [Skilled-Coder/New-jiosaavn-downloader-chrome-extension#2]
Saavn Downloader is Incridible But we also request you to Make One for Gaana.com

**Comment by Skilled-Coder** [comment]
An extension for Ganna.com is coming soon! 
If you like my work, please star this repository.

**Comment by OmkarK45** [comment]
Hey please port this extension to Firefox so it can be used on Android as well ..

**Comment by Skilled-Coder** [comment]
Okay....you can use chrome extensions on android too... 
Search for yandex

**Comment by OmkarK45** [comment]
For some reason in Yandex, it's showing the error 'invalid manifest' when added ..
